[phases.setup]
nixPkgs = ["python312", "google-chrome", "chromedriver"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "chmod +x /usr/local/bin/chromedriver"  # Ensure ChromeDriver is executable
]

[start]
cmd = "python bot.py"